### ISSUE TITLE
normalize_name not defined

### ISSUE THREAD

**Issue by llvasconcellos** [projectbuendia/buendia#54]
Error applying profile: nutrition-chad16-fr-2charts-v2.csv
Traceback (most recent call last):
  File "/usr/bin/buendia-profile-apply", line 525, in <module>
    apply(read_csv(sys.argv[1]))
  File "/usr/bin/buendia-profile-apply", line 521, in apply
    main()
  File "/usr/bin/buendia-profile-apply", line 150, in main
    apply_chart(tabs['chart'], db.get('form_id', uuid=CHART_UUID))
  File "/usr/bin/buendia-profile-apply", line 279, in apply_chart
    apply_chart_sections(sections, form_id)
  File "/usr/bin/buendia-profile-apply", line 320, in apply_chart_sections
    for key, value in row.items() if key],
NameError: global name 'normalize_name' is not defined

**Comment by llvasconcellos** [comment]
[nutrition-chad16-fr-2charts-v2.txt](https://github.com/projectbuendia/buendia/files/90859/nutrition-chad16-fr-2charts-v2.txt)
Profile used.

**Comment by llvasconcellos** [comment]
@capnfabs you could try this profile to see if you have problems syncing Patients.

**Comment by capnfabs** [comment]
Great, thanks.
